# Store used if not specified in the command.
default_store = "file"
default_profile = "default"

[stores.file]
type = "filestore"
# [stores.file.config]
# path = "~/.config/clef/filestore"

[stores.os]
type = "osstore"
[stores.os.config]
namespace = "prod"

[profiles.default]
shell = "nu"
# [[profiles.default.secrets]]
# key = "foo"
# store = "os"
# target = "MY_FOO"
